version: '3'

services:

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks: 
      - nginx-network
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - node-network
      - nginx-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules # Volume anônimo
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
  nginx-network:
    driver: bridge